language: node_js
node_js:
  - 10.6.0
branches:
  only:
    - master
install:
  - npm install -g firebase-tools
  - cd public
  - npm install
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
